### ISSUE TITLE
Cant create Array

### ISSUE THREAD

**Issue by EldosHD** [Deltaphish/UwUpp#7]
I tried creating an array with: `a iws awway<20>`
as suggested in the Wiki. But i get the following error:
`"The program failed to execute: [Error] There was an attempt to use an undeclared variable awway"`

My testfile only contains `a iws awway<20>`

Am I stupid or is the interpreter broken?

**Comment by Deltaphish** [comment]
Both you and the intepreter should be fine, its the docs that are not updated. Right now the proper syntax should be  awway<size;type> where type is "int" or "str". The typechecker is currently more cursed than the actual language, will try to rewrite it soon.

**Comment by EldosHD** [comment]
Oh ok thx for the quick answer. I´ll keep that in mind
Idk if you are still working on this, but if you are, can you add more specific errors to the interpreter? Idk if I overlooked sth in the wiki/usage, but right now the Interpreter just says ERROR: `[the error]`,but not where exactly the error occured. 
Could you please add such feature if that is possible (and you have time of course)?

**Comment by Deltaphish** [comment]
Tracking line number in the interpreter for debugging is kinda tricky, which is why i left it out. But when i try to rewrite everything I can see if I can get it working.

 Don't know when I have time to do that, but I can fix the docs this weekend so others don't stumble on this.
 Thanks for bringing it up 👍

**Comment by EldosHD** [comment]
Than thx for the quick answer. Ill close that issue then
