### ISSUE TITLE
Add documentation for running an UwUpp file

### ISSUE THREAD

**Issue by MaximumMaxxx** [Deltaphish/UwUpp#9]
Installing UwUpp is relatively straight forward with the instructions, however there is no documentation for actually running  an .uwu or .uwupp file. Please add said documentation.

**Comment by EldosHD** [comment]
you just install the UwUpp-exe and then do: `UwUpp-exe FILE.uwu` in the commandline

**Comment by MaximumMaxxx** [comment]
@EldosHD Thanks for that
